version: 6.{build}.0
skip_tags: true
image: Visual Studio 2022
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.exe vs2022 --with-version=%APPVEYOR_BUILD_VERSION%
build:
  project: build/Ultimate-SWO-ModLoader.sln
  verbosity: minimal
before_package:
- cmd: msbuild.exe build/Ultimate-SWO-ModLoader.sln /t:Build /p:Configuration=Release;Platform=x64
artifacts:
- path: bin\Ultimate-SWO-ModLoader.zip
  name: Ultimate-SWO-ModLoader.zip
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Ultimate Star Wars Outlaws ModLoader v$(appveyor_build_version)
  description: This is a DLL file based on Ultimate ASI Loader that adds mod support and ASI plugin loading functionality.
  auth_token:
    secure: ugbti+bXX/7zqu39OyiPxgRPd2pQn2FEV/12ABees2fHfpZob0tWXzqD/zSYmibJ
  artifact: Ultimate-SWO-ModLoader.zip
  prerelease: false
  on:
    branch: undefined